### ISSUE TITLE
CAD Software?

### ISSUE THREAD

**Issue by Spectre5** [willem-pennings/Air-Quality-Sensor#1]
Hello, I'm interested in building this project, or some variation to it.  You've mentioned in the README that the PCB was designed with KiCAD, which I've installed and opened the project with.  I'm also wondering what CAD software was used to create the 3D case?  And what store did you use for printing the PCB board?

Are these sensors continuing to perform well for you?

**Comment by willem-pennings** [comment]
Hi,

I used Siemens NX to design the case. I must admit that this software isn't very well known. One of my friends printed the case for me. I typically use Shapeways otherwise. The sensors are working well for me. This unit runs 24/7 and I've had no issues with the sensors whatsoever. I recommend turning on automatic self calibration on the SCD30 (CO2) sensor such that the value stays accurate over time.

**Comment by Spectre5** [comment]
Ah, ok.  I know of Siemens NX but have no experience with it.  Where did you print the PCB board from?

**Comment by willem-pennings** [comment]
JLCPCB or PCBWay are both fine.

**Comment by Spectre5** [comment]
Thanks for the input!  I've bought the various sensors, so I hope to get something up and running fairly soon.  I'll get it working on a breadboard and then consider moving it to something more permanent.  I may try modeling the case in FreeCAD.
